apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: greeter
    version: "2"
  name: greeter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeter
      version: "2"
  template:
    metadata:
      labels:
        app: greeter
        version: "2"
    spec:
      containers:
        - name: greeter
          image: "javaderek/greeter:stage3"