apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: greeter
    version: "2"
  name: greeter
spec:
  replicas: 3
  selector:
    matchLabels:
      app: greeter
      version: "2"
  template:
    metadata:
      labels:
        app: greeter
        version: "2"
    spec:
      containers:
        - image: javaderek/greeter:stage3
          name: server
          livenessProbe:
            httpGet:
              path: /healthy
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 3
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            requests:
              cpu: "500m"
              memory: "128Mi"
            limits:
              cpu: "1000m"
              memory: "256Mi"