apiVersion: v1
kind: Pod
metadata:
  name: server
spec:
  containers:
    - image: javaderek/greeter:stage3
      name: server
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP