apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: client
    version: "2"
  name: client-v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: client
      version: "2"
  template:
    metadata:
      labels:
        app: client
        version: "2"
    spec:
      containers:
        - image: javaderek/client:stage2
          name: client
          resources:
            requests:
              cpu: "500m"
              memory: "128Mi"
            limits:
              cpu: "1000m"
              memory: "256Mi"
