apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: greeter
    version: "3"
  name: greeter-v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: greeter
      version: "3"
  template:
    metadata:
      labels:
        app: greeter
        version: "3"
    spec:
      containers:
        - image: javaderek/greeter:stage4b
          name: server
          livenessProbe:
            httpGet:
              path: /healthy
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /greeting
              port: 8080
            periodSeconds: 2
            initialDelaySeconds: 5
            failureThreshold: 3
            successThreshold: 1
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            requests:
              cpu: "500m"
              memory: "128Mi"
            limits:
              cpu: "1000m"
              memory: "256Mi"
